logLevel = "warn"
outputs = "all"
position = "top"
appLauncherCmd = "anyrun"
# Команда буфера обмена, будет использоваться для открытия меню буфера обмена,
# без значения соответствующая кнопка не появится
# опционально, по умолчанию None
# clipboardCmd = "cliphist-rofi-img | wl-copy"

truncateTitleAfterLength = 150

# Объявите, какие модули должны использоваться и в какой позиции в строке состояния.
# Это список всех возможных модулей
#  - appLauncher      (Запуск приложений)
#  - updates          (Обновления)
#  - clipboard        (Буфер обмена)
#  - workspaces       (Рабочие столы)
#  - windowTitle      (Заголовок окна)
#  - systemInfo       (Системная информация)
#  - keyboardLayout   (Раскладка клавиатуры)
#  - keyboardSubmap   (Подкарта клавиатуры)
#  - tray             (Системный трей)
#  - clock            (Часы)
#  - privacy          (Приватность)
#  - mediaPlayer      (Медиаплеер)
#  - settings         (Настройки)
# опционально, ниже приведена конфигурация по умолчанию
[modules]
# Модули, которые будут отображаться в левой части строки состояния
left = [["systemInfo", "tray"]]
# Модули, которые будут отображаться в центре строки состояния
center = ["mediaPlayer"]
# Модули, которые будут отображаться в правой части строки состояния
# Вложенный массив модулей сформирует группу, использующую один и тот же элемент в строке состояния
right = [["clock", "settings"]]

# Конфигурация модуля обновлений.
# Без значения соответствующая кнопка не появится.
# опционально, по умолчанию None
[updates]
# Команда проверки будет использоваться для получения списка обновлений.
# Она должна возвращать что-то вроде `имя_пакета версия_от -> версия_до\n`
checkCmd = "checkupdates; paru -Qua"
# Команда обновления используется для инициализации процесса обновления ОС
updateCmd = 'alacritty -e bash -c "paru; echo Done - Press enter to exit; read" &'

# Конфигурация системного модуля
[system]
# уровень предупреждения для индикатора CPU (по умолчанию 60)
cpuWarnThreshold = 60
# уровень тревоги для индикатора CPU (по умолчанию 80)
cpuAlertThreshold = 80
# уровень предупреждения для индикатора памяти (по умолчанию 70)
memWarnThreshold = 70
# уровень тревоги для индикатора памяти (по умолчанию 85)
memAlertThreshold = 85
# уровень предупреждения для индикатора температуры (по умолчанию 60)
tempWarnThreshold = 60
# уровень тревоги для индикатора температуры (по умолчанию 80)
tempAlertThreshold = 80

# Конфигурация модуля часов
[clock]
# формат часов, см.: https://docs.rs/chrono/latest/chrono/format/strftime/index.html
format = "%a %d %b %R" # Например: Пн 01 янв 15:30

# Конфигурация модуля медиаплеера
[mediaPlayer]
# опционально, по умолчанию 100
maxTitleLength = 100

# Конфигурация модуля настроек
[settings]
# команда, используемая для блокировки системы
# без значения соответствующая кнопка не появится
# опционально, по умолчанию None
# lockCmd = "hyprlock &"
# команда, используемая для открытия настроек аудиовыходов (sinks)
# без значения соответствующая кнопка не появится
# опционально, по умолчанию None
audioSinksMoreCmd = "pavucontrol -t 3"
# команда, используемая для открытия настроек аудиовходов (sources)
# без значения соответствующая кнопка не появится
# опционально, по умолчанию None
audioSourcesMoreCmd = "pavucontrol -t 4"
# команда, используемая для открытия настроек сети
# без значения соответствующая кнопка не появится
# опционально, по умолчанию None
wifiMoreCmd = "nm-connection-editor"
# команда, используемая для открытия настроек VPN
# без значения соответствующая кнопка не появится
# опционально, по умолчанию None
vpnMoreCmd = "nm-connection-editor"
# команда, используемая для открытия настроек Bluetooth
# без значения соответствующая кнопка не появится
# опционально, по умолчанию None
bluetoothMoreCmd = "blueman-manager"

# --- Catppuccin Mocha Цвета ---
[appearance]
# опционально, по умолчанию шрифт iced.rs
fontName = "JetBrainsMono Nerd Font"
# Стиль основной панели, возможные значения: islands | solid | gradient
# опционально, по умолчанию islands
style = "islands"
# Прозрачность основной панели, возможные значения: от 0.0 до 1.0
# опционально, по умолчанию 1.0
opacity = 0.7 # Оставил как в оригинале
# используется как базовый цвет фона для кнопок модулей заголовка (Catppuccin Base)
backgroundColor = "#1e1e2e"
# используется как акцентный цвет (Catppuccin Mauve) - можно выбрать другой акцент (Peach #fab387, Blue #89b4fa и т.д.)
primaryColor = "#cba6f7"
# используется для более темного цвета фона (Catppuccin Crust)
secondaryColor = "#11111b"
# используется для сообщений об успехе или "счастливого" состояния (Catppuccin Green)
successColor = "#a6e3a1"
# используется для сообщений об опасности или состояния опасности (Catppuccin Red)
# Слабая версия (для предупреждений) будет автоматически сгенерирована или можно задать явно (Maroon #eba0ac)
dangerColor = "#f38ba8"
# базовый цвет текста по умолчанию (Catppuccin Text)
textColor = "#cdd6f4"
# это список цветов, который будет использоваться в модуле рабочих столов (один цвет для каждого монитора)
# Выбраны некоторые акцентные цвета Catppuccin (Peach, Lavender)
workspaceColors = ["#fab387", "#b4befe"]
# это список цветов, который будет использоваться в модуле рабочих столов
# для специального рабочего стола (один цвет для каждого монитора)
# опционально, по умолчанию None
# без значения будет использоваться список workspaceColors
# Использованы Green и Red из Catppuccin для выделения
specialWorkspaceColors = ["#a6e3a1", "#f38ba8"]

# опции меню
[appearance.menu]
# Прозрачность меню, возможные значения: от 0.0 до 1.0
# опционально, по умолчанию 1.0
opacity = 0.7
# Затемнение фона меню (backdrop), возможные значения: от 0.0 до 1.0
# опционально, по умолчанию 0.0
backdrop = 0.3
